import { BadRequestException, ConflictException, Injectable, NotFoundException, ServiceUnavailableException } from '@nestjs/common';
import { ContentMediaRole, MediaResourceType, NewsletterPublicationStatus } from '@prisma/client';
import { pageResult, pagination } from '../../common/pagination/pagination';
import { PrismaService } from '../../database/prisma.service';
import { EmailService } from '../email/email.service';
import { CampaignDto } from './newsletter.controller';
import { NewsletterSubscriberStatus } from '@prisma/client';
@Injectable() export class NewsletterService {
 constructor(private p:PrismaService,private email:EmailService){}
 async subscribe(email:string,firstName?:string){email=email.trim().toLowerCase();const x=await this.p.newsletterSubscriber.findUnique({where:{email}});if(x){if(x.status!==NewsletterSubscriberStatus.ACTIVE)await this.p.newsletterSubscriber.update({where:{id:x.id},data:{status:NewsletterSubscriberStatus.ACTIVE,unsubscribedAt:null,firstName:firstName??x.firstName}});return{accepted:true}}await this.p.newsletterSubscriber.create({data:{email,firstName,status:NewsletterSubscriberStatus.ACTIVE}});return{accepted:true}}
 async unsubscribe(email:string){const x=await this.p.newsletterSubscriber.findUnique({where:{email:email.trim().toLowerCase()}});if(x)await this.p.newsletterSubscriber.update({where:{id:x.id},data:{status:NewsletterSubscriberStatus.UNSUBSCRIBED,unsubscribedAt:new Date()}});return{accepted:true}}
 async subscribers(q:any){const where:any={...(q.status?{status:q.status}:{}),...(q.search?{email:{contains:q.search,mode:'insensitive'}}:{})};const[items,total]=await Promise.all([this.p.newsletterSubscriber.findMany({where,...pagination(q)}),this.p.newsletterSubscriber.count({where})]);return pageResult(items,total,q)}
 campaign(id:string){return this.p.newsletterCampaign.findUnique({where:{id},include:{deliveries:true,media:{include:{mediaAsset:true},orderBy:{sortOrder:'asc'}}}}).then(x=>{if(!x)throw new NotFoundException({code:'NEWSLETTER_CAMPAIGN_NOT_FOUND',message:'Campaign not found.'});return x})}
 campaigns(q:any){return this.p.newsletterCampaign.findMany({...pagination(q),orderBy:{createdAt:'desc'},include:{media:{include:{mediaAsset:true},orderBy:{sortOrder:'asc'}}}})}
 private async attachments(d:CampaignDto,id:string,tx:any){const gallery=d.galleryMediaAssetIds??[];if(new Set(gallery).size!==gallery.length||(d.thumbnailMediaAssetId&&gallery.includes(d.thumbnailMediaAssetId)))throw new BadRequestException({code:'DUPLICATE_MEDIA_ASSET',message:'Media assets must be unique.'});const ids=[...(d.thumbnailMediaAssetId?[d.thumbnailMediaAssetId]:[]),...gallery];const assets=await tx.mediaAsset.findMany({where:{id:{in:ids}}});if(assets.length!==ids.length||assets.some((x:any)=>x.resourceType!==MediaResourceType.IMAGE))throw new BadRequestException({code:'INVALID_MEDIA_ASSET',message:'Only existing image media assets may be attached.'});await tx.contentMedia.deleteMany({where:{newsletterCampaignId:id}});if(ids.length)await tx.contentMedia.createMany({data:ids.map((mediaAssetId,i)=>({newsletterCampaignId:id,mediaAssetId,role:i===0&&d.thumbnailMediaAssetId?ContentMediaRole.THUMBNAIL:ContentMediaRole.GALLERY,sortOrder:i}))})}
 async createCampaign(d:CampaignDto){const x=await this.p.$transaction(async tx=>{const c=await tx.newsletterCampaign.create({data:{subject:d.subject,content:d.content,slug:d.slug,title:d.title,summary:d.summary,body:d.body as any,videoUrl:d.videoUrl,publicationStatus:d.publicationStatus??NewsletterPublicationStatus.DRAFT,status:d.status??'DRAFT'}});await this.attachments(d,c.id,tx);return c});return this.campaign(x.id)}
 async updateCampaign(id:string,d:CampaignDto){await this.campaign(id);const x=await this.p.$transaction(async tx=>{const c=await tx.newsletterCampaign.update({where:{id},data:{subject:d.subject,content:d.content,slug:d.slug,title:d.title,summary:d.summary,body:d.body as any,videoUrl:d.videoUrl,publicationStatus:d.publicationStatus,status:d.status}});await this.attachments(d,id,tx);return c});return this.campaign(x.id)}
 async publish(id:string){const x=await this.p.newsletterCampaign.update({where:{id},data:{publicationStatus:NewsletterPublicationStatus.PUBLISHED,publishedAt:new Date()}});return x}
 async archive(id:string){return this.p.newsletterCampaign.update({where:{id},data:{publicationStatus:NewsletterPublicationStatus.ARCHIVED}})}
 async publicCampaigns(q:any){const query={page:Number(q?.page)||1,limit:Number(q?.limit)||20,sortOrder:'desc' as const};const where={publicationStatus:NewsletterPublicationStatus.PUBLISHED,publishedAt:{lte:new Date()}};const [items,total]=await Promise.all([this.p.newsletterCampaign.findMany({where,...pagination(query),orderBy:{publishedAt:'desc'},select:{id:true,slug:true,title:true,subject:true,summary:true,body:true,videoUrl:true,publishedAt:true,media:{include:{mediaAsset:true},orderBy:{sortOrder:'asc'}}}}),this.p.newsletterCampaign.count({where})]);return pageResult(items,total,query)}
 async publicCampaign(slug:string){const x=await this.p.newsletterCampaign.findFirst({where:{slug,publicationStatus:NewsletterPublicationStatus.PUBLISHED,publishedAt:{lte:new Date()}},select:{id:true,slug:true,title:true,subject:true,summary:true,body:true,videoUrl:true,publishedAt:true,media:{include:{mediaAsset:true},orderBy:{sortOrder:'asc'}}}});if(!x)throw new NotFoundException({code:'NEWSLETTER_NOT_FOUND',message:'Newsletter not found.'});return x}
 async prepare(id:string){await this.campaign(id);const subs=await this.p.newsletterSubscriber.findMany({where:{status:NewsletterSubscriberStatus.ACTIVE}});for(const s of subs)await this.p.newsletterDelivery.upsert({where:{campaignId_subscriberId:{campaignId:id,subscriberId:s.id}},create:{campaignId:id,subscriberId:s.id},update:{}});return{prepared:subs.length,sent:false}}
 async sendCampaign(id:string){const campaign=await this.campaign(id);if(campaign.status==='SENT')throw new ConflictException({code:'NEWSLETTER_CAMPAIGN_ALREADY_SENT',message:'Campaign has already been sent.'});const subscribers=await this.p.newsletterSubscriber.findMany({where:{status:NewsletterSubscriberStatus.ACTIVE},select:{id:true,email:true}});if(!subscribers.length)throw new NotFoundException({code:'NEWSLETTER_NO_ELIGIBLE_RECIPIENTS',message:'No eligible newsletter recipients.'});let sent=0,failed=0;for(const sub of subscribers){const delivery=await this.p.newsletterDelivery.upsert({where:{campaignId_subscriberId:{campaignId:id,subscriberId:sub.id}},create:{campaignId:id,subscriberId:sub.id},update:{}});if(delivery.deliveredAt)continue;try{await this.email.sendNewsletterEmail(sub.email,campaign.subject,campaign.content);await this.p.newsletterDelivery.update({where:{id:delivery.id},data:{deliveredAt:new Date(),failedAt:null,errorMessage:null}});sent++}catch{await this.p.newsletterDelivery.update({where:{id:delivery.id},data:{failedAt:new Date(),errorMessage:'EMAIL_DELIVERY_FAILED'}});failed++}}if(!sent&&failed)throw new ServiceUnavailableException({code:'NEWSLETTER_DELIVERY_FAILED',message:'Newsletter delivery failed.'});await this.p.newsletterCampaign.update({where:{id},data:{status:failed?'PARTIALLY_SENT':'SENT',sentAt:new Date()}});return{sent,failed}}
}
