import { Type } from 'class-transformer'; import { IsArray, IsBoolean, IsDateString, IsEnum, IsInt, IsOptional, IsString, IsUrl, Length, Max, Min } from 'class-validator'; import { ActivityType, CourseBookingStatus, ProgramStatus, ProgramType, SessionLevel, SessionStatus } from '@prisma/client'; import { PaginationDto } from '../../../common/pagination/pagination.dto';
export class ProgramQueryDto extends PaginationDto { @IsOptional() @IsEnum(ProgramType) type?:ProgramType; @IsOptional() @IsString() @Length(1,100) search?:string; @IsOptional() @IsString() sortBy?:'title'|'createdAt'; }
export class SessionQueryDto extends PaginationDto { @IsOptional() @IsString() programId?:string; @IsOptional() @IsEnum(ProgramType) programType?:ProgramType; @IsOptional() @IsString() instructorId?:string; @IsOptional() @IsDateString() from?:string; @IsOptional() @IsDateString() to?:string; @IsOptional() @IsEnum(SessionLevel) level?:SessionLevel; @IsOptional() @IsString() timeOfDay?:'morning'|'evening'; }
export class ProgramDto { @IsString() @Length(1,180) slug!:string; @IsString() @Length(1,200) title!:string; @IsEnum(ProgramType) type!:ProgramType; @IsOptional() @IsString() shortDescription?:string; @IsOptional() @IsString() description?:string; @IsOptional() @IsUrl() coverImageUrl?:string; @IsOptional() @IsEnum(ProgramStatus) status?:ProgramStatus; }
export class InstructorDto { @IsOptional() @IsString() userId?:string; @IsString() @Length(1,160) slug!:string; @IsString() @Length(1,160) displayName!:string; @IsOptional() @IsString() headline?:string; @IsOptional() @IsString() biography?:string; @IsOptional() @IsUrl() photoUrl?:string; @IsOptional() @IsArray() @IsString({each:true}) specialties?:string[]; @IsOptional() @Type(()=>Number) @IsInt() @Min(0) @Max(100) yearsExperience?:number; @IsOptional() @IsBoolean() isPublished?:boolean; }
export class SessionDto { @IsString() programId!:string; @IsOptional() @IsString() instructorId?:string|null; @IsString() @Length(1,200) title!:string; @IsDateString() sessionDate!:string; @IsDateString() startAt!:string; @IsDateString() endAt!:string; @IsOptional() @IsString() @Length(1,100) timezone?:string; @IsOptional() @IsEnum(SessionLevel) level?:SessionLevel; @Type(()=>Number) @IsInt() @Min(1) @Max(10000) capacity!:number; @IsOptional() @IsString() location?:string; @IsOptional() @IsUrl() meetingUrl?:string; @IsOptional() @IsEnum(SessionStatus) status?:SessionStatus; @IsOptional() @IsString() cancellationNote?:string; }
export class CreateBookingDto { @IsString() programSessionId!:string; } export class BookingQueryDto extends PaginationDto { @IsOptional() @IsEnum(CourseBookingStatus) status?:CourseBookingStatus; @IsOptional() @IsBoolean() @Type(()=>Boolean) upcoming?:boolean; }
export class BookingStatusDto { @IsEnum(CourseBookingStatus) status!:CourseBookingStatus; } export class AssignInstructorDto { @IsString() instructorId!:string; @IsOptional() @IsBoolean() isLead?:boolean; }
export class PracticeDto { @IsEnum(ActivityType) activityType!:ActivityType; @IsOptional() @IsString() programSessionId?:string; @IsDateString() startedAt!:string; @IsOptional() @IsDateString() endedAt?:string; @Type(()=>Number) @IsInt() @Min(0) @Max(1440) durationMinutes!:number; @IsOptional() @IsString() @Length(1,5000) notes?:string; }
