import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { OrderStatus, PaymentPurpose, PaymentStatus, Prisma, ProductStatus } from '@prisma/client';
import { AuditService } from '../../common/audit/audit.service'; import { pageResult, pagination } from '../../common/pagination/pagination'; import { PrismaService } from '../../database/prisma.service'; import { EmailService } from '../email/email.service'; import { PaymentsService } from '../payments/payments.service'; import * as D from './dto/store.dto';
const decimal=(v:Prisma.Decimal|string|number)=>new Prisma.Decimal(v); const money=(v:Prisma.Decimal)=>v.toDecimalPlaces(2);
const activePayments=[PaymentStatus.CREATED,PaymentStatus.PENDING,PaymentStatus.AUTHORIZED];
@Injectable() export class StoreService {
 constructor(private readonly prisma:PrismaService,private readonly audit:AuditService,private readonly payments:PaymentsService,private readonly email:EmailService) {}
 private fail(code:string,message:string){throw new BadRequestException({code,message})} private async category(id:string){const x=await this.prisma.productCategory.findUnique({where:{id}});if(!x)throw new NotFoundException({code:'CATEGORY_NOT_FOUND',message:'Category not found.'});return x}
 async categories(){return this.prisma.productCategory.findMany({where:{},select:{id:true,name:true,slug:true,parent:{select:{id:true,name:true,slug:true}},children:{select:{id:true,name:true,slug:true}}},orderBy:{name:'asc'}})}
 async products(q:D.CatalogQueryDto){const where:Prisma.ProductWhereInput={status:ProductStatus.ACTIVE,...(q.category?{category:{is:{OR:[{id:q.category},{slug:q.category}]}}}:{}),...(q.search?{OR:[{name:{contains:q.search,mode:'insensitive'}},{description:{contains:q.search,mode:'insensitive'}}]}:{})};const [items,total]=await Promise.all([this.prisma.product.findMany({where,...pagination(q),orderBy:{[q.sortBy==='name'?'name':q.sortBy==='updatedAt'?'updatedAt':'createdAt']:q.sortOrder},include:{category:{select:{id:true,name:true,slug:true}},images:{orderBy:{sortOrder:'asc'}},variants:{include:{inventory:{select:{quantityOnHand:true}}}}}}),this.prisma.product.count({where})]);return pageResult(items.map(this.publicProduct),total,q)}
 async product(slug:string){const p=await this.prisma.product.findFirst({where:{status:ProductStatus.ACTIVE,OR:[{id:slug},{slug}]},include:{category:true,images:{orderBy:{sortOrder:'asc'}},variants:{include:{inventory:{select:{quantityOnHand:true}}}}}});if(!p)throw new NotFoundException({code:'PRODUCT_NOT_FOUND',message:'Product not found.'});return this.publicProduct(p)}
 private publicProduct=(p:any)=>({...p,variants:p.variants?.map((v:any)=>({id:v.id,name:v.name,sku:v.sku,price:v.price,currency:v.currency,attributes:v.attributes,availableQuantity:Math.max(0,(v.inventory?.quantityOnHand??0)-(v.inventory?.quantityReserved??0)),inStock:(v.inventory?.quantityOnHand??0)>0}))})
 private identity(userId?:string,sessionId?:string):{userId?:string;sessionId?:string}{if(userId)return {userId};if(sessionId&&/^[A-Za-z0-9_-]{8,100}$/.test(sessionId))return {sessionId};this.fail('CART_NOT_FOUND','Sign in or provide a valid X-Cart-Session-Id header.');throw new Error('unreachable');}
 private async cart(userId?:string,sessionId?:string){const identity=this.identity(userId,sessionId);let c=await this.prisma.cart.findFirst({where:identity});if(!c)c=await this.prisma.cart.create({data:identity});return c}
 private async cartData(userId?:string,sessionId?:string){const c=await this.cart(userId,sessionId);return this.prisma.cart.findUniqueOrThrow({where:{id:c.id},include:{items:{include:{productVariant:{include:{product:true,inventory:true}}}}}})}
 private cartResponse(c:any){let subtotal=decimal(0),count=0;const items=c.items.map((i:any)=>{const available=Math.max(0,(i.productVariant.inventory?.quantityOnHand??0)-(i.productVariant.inventory?.quantityReserved??0));const total=money(decimal(i.productVariant.price).mul(i.quantity));subtotal=subtotal.add(total);count+=i.quantity;return {id:i.id,quantity:i.quantity,variant:{id:i.productVariant.id,name:i.productVariant.name,sku:i.productVariant.sku,price:i.productVariant.price,currency:i.productVariant.currency,product:{id:i.productVariant.product.id,name:i.productVariant.product.name,slug:i.productVariant.product.slug}},lineTotal:total,availableQuantity:available}});return {id:c.id,currency:c.currency,items,subtotal:money(subtotal),itemCount:count}}
 async getCart(userId?:string,sessionId?:string){return this.cartResponse(await this.cartData(userId,sessionId))}
 private async sellable(id:string){const v=await this.prisma.productVariant.findUnique({where:{id},include:{product:true,inventory:true}});if(!v)throw new NotFoundException({code:'VARIANT_NOT_FOUND',message:'Variant not found.'});if(v.product.status!==ProductStatus.ACTIVE)this.fail('PRODUCT_NOT_AVAILABLE','Product is not available.');return v}
 private stock(v:any,q:number){const a=Math.max(0,(v.inventory?.quantityOnHand??0)-(v.inventory?.quantityReserved??0));if(q>a)this.fail('INSUFFICIENT_STOCK',`Only ${a} item(s) are available.`)}
 async addCartItem(userId:string|undefined,sessionId:string|undefined,d:D.CartItemDto){const c=await this.cart(userId,sessionId),v=await this.sellable(d.variantId);const existing=await this.prisma.cartItem.findUnique({where:{cartId_productVariantId:{cartId:c.id,productVariantId:v.id}}});this.stock(v,d.quantity+(existing?.quantity??0));await this.prisma.cartItem.upsert({where:{cartId_productVariantId:{cartId:c.id,productVariantId:v.id}},create:{cartId:c.id,productVariantId:v.id,quantity:d.quantity},update:{quantity:{increment:d.quantity}}});return this.getCart(userId,sessionId)}
 async updateCartItem(userId:string|undefined,sessionId:string|undefined,id:string,d:D.UpdateCartItemDto){const c=await this.cart(userId,sessionId),i=await this.prisma.cartItem.findFirst({where:{id,cartId:c.id}});if(!i)throw new NotFoundException({code:'CART_ITEM_NOT_FOUND',message:'Cart item not found.'});this.stock(await this.sellable(i.productVariantId),d.quantity);await this.prisma.cartItem.update({where:{id},data:{quantity:d.quantity}});return this.getCart(userId,sessionId)}
 async removeCartItem(userId:string|undefined,sessionId:string|undefined,id:string){const c=await this.cart(userId,sessionId);const x=await this.prisma.cartItem.deleteMany({where:{id,cartId:c.id}});if(!x.count)throw new NotFoundException({code:'CART_ITEM_NOT_FOUND',message:'Cart item not found.'});return this.getCart(userId,sessionId)} async clearCart(userId?:string,sessionId?:string){const c=await this.cart(userId,sessionId);await this.prisma.cartItem.deleteMany({where:{cartId:c.id}});return {cleared:true}}
 private async validCart(userId:string){const c=await this.cartData(userId);if(!c.items.length)this.fail('CART_EMPTY','Cart is empty.');for(const i of c.items){if(i.productVariant.product.status!==ProductStatus.ACTIVE)this.fail('PRODUCT_NOT_AVAILABLE','A cart product is no longer available.');this.stock(i.productVariant,i.quantity)}return c}
 private totals(c:any){const subtotal=money(c.items.reduce((x:any,i:any)=>x.add(decimal(i.productVariant.price).mul(i.quantity)),decimal(0)));return {subtotal,taxAmount:decimal(0),discountAmount:decimal(0),shippingAmount:decimal(0),totalAmount:subtotal,currency:c.currency}}
 async preview(userId:string,d:D.CheckoutDto){const c=await this.validCart(userId);return {cart:this.cartResponse(c),...this.totals(c),shippingAddress:d.shippingAddress,billingAddress:d.billingAddress??d.shippingAddress}}
 async createOrder(userId:string,d:D.CheckoutDto){const c=await this.validCart(userId);const totals=this.totals(c);const user=await this.prisma.user.findUnique({where:{id:userId},select:{email:true}});if(!user)throw new ForbiddenException({code:'ORDER_ACCESS_DENIED',message:'User not found.'});const number=`ORD-${Date.now()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;const order=await this.prisma.$transaction(async tx=>{for(const i of c.items){const affected=await tx.inventory.updateMany({where:{productVariantId:i.productVariantId,quantityOnHand:{gte:i.quantity}},data:{quantityOnHand:{decrement:i.quantity}}});if(affected.count!==1)this.fail('INSUFFICIENT_STOCK','Stock changed before checkout; please review your cart.')}const order=await tx.order.create({data:{orderNumber:number,userId,email:user.email,...totals,items:{create:c.items.map((i:any)=>({productId:i.productVariant.productId,productVariantId:i.productVariantId,productName:i.productVariant.product.name,variantName:i.productVariant.name,sku:i.productVariant.sku,quantity:i.quantity,unitPrice:i.productVariant.price,total:money(decimal(i.productVariant.price).mul(i.quantity))}))},addresses:{create:[{type:'SHIPPING',...d.shippingAddress},{type:'BILLING',...(d.billingAddress??d.shippingAddress)}]}},include:{items:true,addresses:true}});await tx.cartItem.deleteMany({where:{cartId:c.id}});return order});void this.email.sendNonBlocking('order-created',order.email,{orderNumber:order.orderNumber,amount:order.totalAmount.toString()},{entityId:order.id});return order}
 async orders(userId:string,q:D.OrderQueryDto){const where={userId,...(q.status?{status:q.status}:{})};const [items,total]=await Promise.all([this.prisma.order.findMany({where,...pagination(q),orderBy:{createdAt:q.sortOrder},include:{items:true}}),this.prisma.order.count({where})]);return pageResult(items,total,q)}
 async order(userId:string,id:string,admin=false){const o=await this.prisma.order.findUnique({where:{id},include:{items:true,addresses:true}});if(!o)throw new NotFoundException({code:'ORDER_NOT_FOUND',message:'Order not found.'});if(!admin&&o.userId!==userId)throw new ForbiddenException({code:'ORDER_ACCESS_DENIED',message:'Order access denied.'});const payments=await this.prisma.payment.findMany({where:{purpose:PaymentPurpose.STORE_ORDER,relatedEntityId:id},select:{id:true,paymentReference:true,status:true,amount:true,currency:true,createdAt:true}});return {...o,payments}}
 private allowed(a:OrderStatus,b:OrderStatus){return a===b||({PENDING:[OrderStatus.CONFIRMED,OrderStatus.CANCELLED],CONFIRMED:[OrderStatus.PROCESSING,OrderStatus.CANCELLED],PROCESSING:[OrderStatus.SHIPPED],SHIPPED:[OrderStatus.DELIVERED],DELIVERED:[OrderStatus.RETURNED],CANCELLED:[],RETURNED:[]} as any)[a].includes(b)}
 private async restock(tx:any,o:any){for(const i of o.items){if(i.productVariantId)await tx.inventory.updateMany({where:{productVariantId:i.productVariantId},data:{quantityOnHand:{increment:i.quantity}}})}}
 async cancel(userId:string,id:string){const saved=await this.prisma.$transaction(async tx=>{const o=await tx.order.findUnique({where:{id},include:{items:true}});if(!o)throw new NotFoundException({code:'ORDER_NOT_FOUND',message:'Order not found.'});if(o.userId!==userId)throw new ForbiddenException({code:'ORDER_ACCESS_DENIED',message:'Order access denied.'});if(o.status!==OrderStatus.PENDING)this.fail('ORDER_CANCELLATION_NOT_ALLOWED','Only pending orders can be cancelled.');const paid=await tx.payment.count({where:{purpose:PaymentPurpose.STORE_ORDER,relatedEntityId:id,status:PaymentStatus.CAPTURED}});if(paid)this.fail('ORDER_CANCELLATION_NOT_ALLOWED','Captured payments require an admin refund flow.');const saved=await tx.order.update({where:{id},data:{status:OrderStatus.CANCELLED}});await this.restock(tx,o);return saved});void this.email.sendNonBlocking('order-cancelled',saved.email,{orderNumber:saved.orderNumber},{entityId:saved.id});return {cancelled:true}}
 async createStorePayment(userId:string,orderId:string){const o=await this.prisma.order.findFirst({where:{id:orderId,userId}});if(!o||o.status!==OrderStatus.PENDING)this.fail('STORE_PAYMENT_NOT_ALLOWED','This order cannot be paid.');return this.payments.createForStoreOrder(userId,orderId)}
 async adminCategories(){return this.categories()} async createCategory(actor:string,d:D.CategoryDto){if(d.parentId)await this.category(d.parentId);try{const x=await this.prisma.productCategory.create({data:d});await this.audit.record({actorId:actor,action:'STORE_CATEGORY_CREATED',entityType:'ProductCategory',entityId:x.id,newValues:d as unknown as Prisma.InputJsonValue});return x}catch{throw new ConflictException({code:'CATEGORY_SLUG_ALREADY_EXISTS',message:'Category slug already exists.'})}}
 async updateCategory(actor:string,id:string,d:D.UpdateCategoryDto){await this.category(id);if(d.parentId){if(d.parentId===id)this.fail('CATEGORY_HIERARCHY_INVALID','A category cannot be its own parent.');let node=await this.prisma.productCategory.findUnique({where:{id:d.parentId}});while(node){if(node.id===id)this.fail('CATEGORY_HIERARCHY_INVALID','A category cannot be moved under its descendant.');node=node.parentId?await this.prisma.productCategory.findUnique({where:{id:node.parentId}}):null}}const x=await this.prisma.productCategory.update({where:{id},data:d});await this.audit.record({actorId:actor,action:'STORE_CATEGORY_UPDATED',entityType:'ProductCategory',entityId:id,newValues:d as unknown as Prisma.InputJsonValue});return x}
 async deleteCategory(actor:string,id:string){const c=await this.category(id);const [children,products]=await Promise.all([this.prisma.productCategory.count({where:{parentId:id}}),this.prisma.product.count({where:{categoryId:id}})]);if(children||products)this.fail('CATEGORY_DELETE_NOT_ALLOWED','Categories with children or products cannot be deleted.');await this.prisma.productCategory.delete({where:{id}});await this.audit.record({actorId:actor,action:'STORE_CATEGORY_DELETED',entityType:'ProductCategory',entityId:id,oldValues:{name:c.name}});return {deleted:true}}
 async adminProducts(q:D.CatalogQueryDto){const where:Prisma.ProductWhereInput={...(q.category?{categoryId:q.category}:{}),...(q.search?{OR:[{name:{contains:q.search,mode:'insensitive'}},{slug:{contains:q.search,mode:'insensitive'}}]}:{})};const [items,total]=await Promise.all([this.prisma.product.findMany({where,...pagination(q),include:{category:true,variants:{include:{inventory:true}},images:true}}),this.prisma.product.count({where})]);return pageResult(items,total,q)}
 async adminProduct(id:string){const x=await this.prisma.product.findUnique({where:{id},include:{category:true,variants:{include:{inventory:true}},images:{orderBy:{sortOrder:'asc'}}}});if(!x)throw new NotFoundException({code:'PRODUCT_NOT_FOUND',message:'Product not found.'});return x}
 async createProduct(a:string,d:D.ProductDto){if(d.categoryId)await this.category(d.categoryId);const x=await this.prisma.product.create({data:{...d,status:d.status??ProductStatus.DRAFT}});await this.audit.record({actorId:a,action:'STORE_PRODUCT_CREATED',entityType:'Product',entityId:x.id,newValues:d as unknown as Prisma.InputJsonValue});return x} async updateProduct(a:string,id:string,d:D.ProductDto){if(d.categoryId)await this.category(d.categoryId);const x=await this.prisma.product.update({where:{id},data:d});await this.audit.record({actorId:a,action:'STORE_PRODUCT_UPDATED',entityType:'Product',entityId:id,newValues:d as unknown as Prisma.InputJsonValue});return x}
 async archiveProduct(a:string,id:string){const x=await this.adminProduct(id);await this.prisma.product.update({where:{id},data:{status:ProductStatus.ARCHIVED}});await this.audit.record({actorId:a,action:'STORE_PRODUCT_ARCHIVED',entityType:'Product',entityId:id,oldValues:{status:x.status}});return {archived:true}}
 async variants(productId:string){await this.adminProduct(productId);return this.prisma.productVariant.findMany({where:{productId},include:{inventory:true}})} async createVariant(a:string,productId:string,d:D.VariantDto){await this.adminProduct(productId);try{const x=await this.prisma.productVariant.create({data:{...d,productId,attributes:d.attributes as Prisma.InputJsonValue,inventory:{create:{quantityOnHand:0}}},include:{inventory:true}});await this.audit.record({actorId:a,action:'STORE_VARIANT_CREATED',entityType:'ProductVariant',entityId:x.id,newValues:d as unknown as Prisma.InputJsonValue});return x}catch{throw new ConflictException({code:'SKU_ALREADY_EXISTS',message:'SKU already exists.'})}}
 async updateVariant(a:string,id:string,d:D.UpdateVariantDto){const v=await this.prisma.productVariant.findUnique({where:{id}});if(!v)throw new NotFoundException({code:'VARIANT_NOT_FOUND',message:'Variant not found.'});try{const x=await this.prisma.productVariant.update({where:{id},data:{...d,attributes:d.attributes as Prisma.InputJsonValue}});await this.audit.record({actorId:a,action:'STORE_VARIANT_UPDATED',entityType:'ProductVariant',entityId:id,newValues:d as unknown as Prisma.InputJsonValue});return x}catch{throw new ConflictException({code:'SKU_ALREADY_EXISTS',message:'SKU already exists.'})}}
 async deleteVariant(a:string,id:string){const history=await this.prisma.orderItem.count({where:{productVariantId:id}});if(history)this.fail('VARIANT_DELETE_NOT_ALLOWED','Variants with order history cannot be deleted.');await this.prisma.productVariant.delete({where:{id}});await this.audit.record({actorId:a,action:'STORE_VARIANT_DELETED',entityType:'ProductVariant',entityId:id});return {deleted:true}}
 async inventory(id?:string){return this.prisma.inventory.findMany({where:id?{productVariantId:id}:{},include:{variant:{include:{product:true}}}})} async adjustInventory(a:string,id:string,d:D.InventoryAdjustmentDto){const i=await this.prisma.inventory.findUnique({where:{productVariantId:id}});if(!i)throw new NotFoundException({code:'VARIANT_NOT_FOUND',message:'Inventory not found.'});if(i.quantityOnHand+d.delta<0)this.fail('INVENTORY_UPDATE_INVALID','Adjustment would make stock negative.');const x=await this.prisma.inventory.update({where:{productVariantId:id},data:{quantityOnHand:{increment:d.delta}}});await this.audit.record({actorId:a,action:'STORE_INVENTORY_ADJUSTED',entityType:'Inventory',entityId:x.id,oldValues:{quantityOnHand:i.quantityOnHand},newValues:{quantityOnHand:x.quantityOnHand,reason:d.reason}});return x}
 async addImage(a:string,productId:string,d:D.ImageDto){await this.adminProduct(productId);const x=await this.prisma.productImage.create({data:{productId,...d}});await this.audit.record({actorId:a,action:'STORE_IMAGE_CREATED',entityType:'ProductImage',entityId:x.id,newValues:d as unknown as Prisma.InputJsonValue});return x} async updateImage(a:string,id:string,d:D.UpdateImageDto){const x=await this.prisma.productImage.update({where:{id},data:d});await this.audit.record({actorId:a,action:'STORE_IMAGE_UPDATED',entityType:'ProductImage',entityId:id,newValues:d as unknown as Prisma.InputJsonValue});return x} async deleteImage(a:string,id:string){await this.prisma.productImage.delete({where:{id}});await this.audit.record({actorId:a,action:'STORE_IMAGE_DELETED',entityType:'ProductImage',entityId:id});return {deleted:true}}
 async adminOrders(q:D.AdminOrderQueryDto){const where:Prisma.OrderWhereInput={...(q.status?{status:q.status}:{}),...(q.search?{OR:[{orderNumber:{contains:q.search,mode:'insensitive'}},{email:{contains:q.search,mode:'insensitive'}}]}:{}),...(q.from||q.to?{createdAt:{...(q.from?{gte:new Date(q.from)}:{}),...(q.to?{lte:new Date(q.to)}:{})}}:{})};const [items,total]=await Promise.all([this.prisma.order.findMany({where,...pagination(q),include:{items:true}}),this.prisma.order.count({where})]);return pageResult(items,total,q)}
 async adminOrderStatus(a:string,id:string,status:OrderStatus){const result=await this.prisma.$transaction(async tx=>{const o=await tx.order.findUnique({where:{id},include:{items:true}});if(!o)throw new NotFoundException({code:'ORDER_NOT_FOUND',message:'Order not found.'});if(o.status===status)return {response:{id,status,unchanged:true},order:null};if(!this.allowed(o.status,status))this.fail('INVALID_ORDER_STATUS_TRANSITION','Invalid order status transition.');if(status===OrderStatus.CANCELLED){const paid=await tx.payment.count({where:{purpose:PaymentPurpose.STORE_ORDER,relatedEntityId:id,status:PaymentStatus.CAPTURED}});if(paid)this.fail('ORDER_CANCELLATION_NOT_ALLOWED','Captured payments require a refund flow.')}const saved=await tx.order.update({where:{id},data:{status}});if(status===OrderStatus.CANCELLED)await this.restock(tx,o);await this.audit.record({actorId:a,action:'STORE_ORDER_STATUS_CHANGED',entityType:'Order',entityId:id,oldValues:{status:o.status},newValues:{status}},tx);return {response:{id,status},order:saved}});if(result.order&&status===OrderStatus.SHIPPED)void this.email.sendNonBlocking('order-shipped',result.order.email,{orderNumber:result.order.orderNumber},{entityId:result.order.id});if(result.order&&status===OrderStatus.CANCELLED)void this.email.sendNonBlocking('order-cancelled',result.order.email,{orderNumber:result.order.orderNumber},{entityId:result.order.id});return result.response}
}
