import { Body, Controller, Delete, Get, Headers, Param, Patch, Post, Query, Req, Version } from '@nestjs/common'; import { RoleName } from '@prisma/client'; import { Public } from '../auth/decorators/public.decorator'; import { Roles } from '../auth/decorators/roles.decorator'; import { CurrentUser } from '../auth/decorators/current-user.decorator'; import { AuthenticatedUser } from '../auth/types/authenticated-user.type'; import { StoreService } from './store.service'; import * as D from './dto/store.dto';
const session=(s?:string)=>s;
@Controller() export class StoreController { constructor(private s:StoreService){} @Public() @Get('store/categories') @Version('1') categories(){return this.s.categories()} @Public() @Get('store/products') @Version('1') products(@Query()q:D.CatalogQueryDto){return this.s.products(q)} @Public() @Get('store/products/:slug') @Version('1') product(@Param('slug')x:string){return this.s.product(x)}
 @Public() @Get('cart') @Version('1') cart(@Req()r:any,@Headers('x-cart-session-id')x?:string){return this.s.getCart(r.user?.id,session(x))} @Public() @Post('cart/items') @Version('1') add(@Req()r:any,@Headers('x-cart-session-id')x:string|undefined,@Body()d:D.CartItemDto){return this.s.addCartItem(r.user?.id,session(x),d)} @Public() @Patch('cart/items/:id') @Version('1') update(@Req()r:any,@Headers('x-cart-session-id')x:string|undefined,@Param('id')id:string,@Body()d:D.UpdateCartItemDto){return this.s.updateCartItem(r.user?.id,session(x),id,d)} @Public() @Delete('cart/items/:id') @Version('1') remove(@Req()r:any,@Headers('x-cart-session-id')x:string|undefined,@Param('id')id:string){return this.s.removeCartItem(r.user?.id,session(x),id)} @Public() @Delete('cart') @Version('1') clear(@Req()r:any,@Headers('x-cart-session-id')x:string|undefined){return this.s.clearCart(r.user?.id,session(x))}
 @Post('store/checkout/preview') @Version('1') preview(@CurrentUser()u:AuthenticatedUser,@Body()d:D.CheckoutDto){return this.s.preview(u.id,d)} @Post('store/orders') @Version('1') order(@CurrentUser()u:AuthenticatedUser,@Body()d:D.CheckoutDto){return this.s.createOrder(u.id,d)} @Get('store/orders') @Version('1') orders(@CurrentUser()u:AuthenticatedUser,@Query()q:D.OrderQueryDto){return this.s.orders(u.id,q)} @Get('store/orders/:id') @Version('1') getOrder(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string){return this.s.order(u.id,id)} @Post('store/orders/:id/cancel') @Version('1') cancel(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string){return this.s.cancel(u.id,id)} @Post('store/orders/:id/payment') @Version('1') payment(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string){return this.s.createStorePayment(u.id,id)} }
@Controller('admin/store') @Roles(RoleName.ADMIN) export class AdminStoreController { constructor(private s:StoreService){} @Get('categories') @Version('1') cats(){return this.s.adminCategories()} @Post('categories') @Version('1') createCat(@CurrentUser()u:AuthenticatedUser,@Body()d:D.CategoryDto){return this.s.createCategory(u.id,d)} @Patch('categories/:id') @Version('1') updateCat(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdateCategoryDto){return this.s.updateCategory(u.id,id,d)} @Delete('categories/:id') @Version('1') deleteCat(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string){return this.s.deleteCategory(u.id,id)}
 @Get('products') @Version('1') products(@Query()q:D.CatalogQueryDto){return this.s.adminProducts(q)} @Post('products') @Version('1') createProduct(@CurrentUser()u:AuthenticatedUser,@Body()d:D.ProductDto){return this.s.createProduct(u.id,d)} @Get('products/:id') @Version('1') product(@Param('id')id:string){return this.s.adminProduct(id)} @Patch('products/:id') @Version('1') updateProduct(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:D.ProductDto){return this.s.updateProduct(u.id,id,d)} @Delete('products/:id') @Version('1') archive(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string){return this.s.archiveProduct(u.id,id)}
 @Get('products/:id/variants') @Version('1') variants(@Param('id')id:string){return this.s.variants(id)} @Post('products/:id/variants') @Version('1') addVariant(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:D.VariantDto){return this.s.createVariant(u.id,id,d)} @Patch('variants/:id') @Version('1') updateVariant(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdateVariantDto){return this.s.updateVariant(u.id,id,d)} @Delete('variants/:id') @Version('1') deleteVariant(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string){return this.s.deleteVariant(u.id,id)}
 @Get('inventory') @Version('1') inventory(){return this.s.inventory()} @Get('variants/:id/inventory') @Version('1') inventoryOne(@Param('id')id:string){return this.s.inventory(id)} @Post('variants/:id/inventory/adjust') @Version('1') adjust(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:D.InventoryAdjustmentDto){return this.s.adjustInventory(u.id,id,d)}
 @Post('products/:id/images') @Version('1') addImage(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:D.ImageDto){return this.s.addImage(u.id,id,d)} @Patch('images/:id') @Version('1') updateImage(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdateImageDto){return this.s.updateImage(u.id,id,d)} @Delete('images/:id') @Version('1') deleteImage(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string){return this.s.deleteImage(u.id,id)}
 @Get('orders') @Version('1') orders(@Query()q:D.AdminOrderQueryDto){return this.s.adminOrders(q)} @Get('orders/:id') @Version('1') order(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string){return this.s.order(u.id,id,true)} @Patch('orders/:id/status') @Version('1') status(@CurrentUser()u:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdateOrderStatusDto){return this.s.adminOrderStatus(u.id,id,d.status)} }
