import { BadRequestException, Injectable, NotFoundException, ServiceUnavailableException } from '@nestjs/common';
import { Prisma, RoleName, UserStatus } from '@prisma/client';
import { AuditService } from '../../common/audit/audit.service';
import { pageResult, pagination } from '../../common/pagination/pagination';
import { PrismaService } from '../../database/prisma.service';
import { AuditLogQueryDto } from './dto/audit-log-query.dto';
import { AdminUsersQueryDto } from './dto/admin-users-query.dto';
import { CreateMediaDto, UpdateMediaDto } from './dto/media.dto';
import { UpdateSettingDto } from './dto/setting.dto';
import { UpdateUserRolesDto } from './dto/update-user-roles.dto';
import { UpdateUserStatusDto } from './dto/update-user-status.dto';
import { MediaStorageService } from './media-storage.service';

const adminUserSelect = { id: true, email: true, emailVerifiedAt: true, status: true, lastLoginAt: true, createdAt: true, roles: { select: { role: { select: { name: true } } } }, profile: { select: { firstName: true, lastName: true, phone: true, countryCode: true, city: true, dateOfBirth: true, avatarUrl: true, bio: true } } } as const;
const publicSettings = ['site.identity', 'contact.info', 'pwa.config', 'feature.public'] as const;
@Injectable()
export class AdminService {
 constructor(private readonly prisma: PrismaService, private readonly audit: AuditService, private readonly storage: MediaStorageService = null as any) {}
 private presentUser(user: { roles: { role: { name: RoleName } }[] }) { return { ...user, roles: user.roles.map(({ role }) => role.name) }; }
 async users(query: AdminUsersQueryDto) { const search = query.search?.trim(); const where: Prisma.UserWhereInput = { ...(query.status ? { status: query.status } : {}), ...(query.role ? { roles: { some: { role: { name: query.role } } } } : {}), ...(search ? { OR: [{ email: { contains: search, mode: 'insensitive' } }, { profile: { is: { OR: [{ firstName: { contains: search, mode: 'insensitive' } }, { lastName: { contains: search, mode: 'insensitive' } }, { phone: { contains: search, mode: 'insensitive' } }] } } }] } : {}) }; const [items, total] = await Promise.all([this.prisma.user.findMany({ where, ...pagination(query), select: adminUserSelect, orderBy: { [query.sortBy]: query.sortOrder } }), this.prisma.user.count({ where })]); return pageResult(items.map((user) => this.presentUser(user)), total, query); }
 async user(id: string) { const user = await this.prisma.user.findUnique({ where: { id }, select: adminUserSelect }); if (!user) throw new NotFoundException({ code: 'USER_NOT_FOUND', message: 'User not found.' }); return this.presentUser(user); }
 async updateStatus(actorId: string, id: string, dto: UpdateUserStatusDto) { if (!( [UserStatus.ACTIVE, UserStatus.SUSPENDED, UserStatus.DISABLED] as UserStatus[]).includes(dto.status)) throw new BadRequestException({ code: 'INVALID_USER_STATUS', message: 'Invalid user status.' }); await this.prisma.$transaction(async (tx) => { const user = await tx.user.findUnique({ where: { id } }); if (!user) throw new NotFoundException({ code: 'USER_NOT_FOUND', message: 'User not found.' }); await tx.user.update({ where: { id }, data: { status: dto.status } }); await this.audit.record({ actorId, action: 'USER_STATUS_CHANGED', entityType: 'User', entityId: id, oldValues: { status: user.status }, newValues: { status: dto.status } }, tx); }); return this.user(id); }
 async updateRoles(actorId: string, id: string, dto: UpdateUserRolesDto) { const requested = [...new Set([...dto.roles, RoleName.USER])]; await this.prisma.$transaction(async (tx) => { const user = await tx.user.findUnique({ where: { id }, include: { roles: { include: { role: true } } } }); if (!user) throw new NotFoundException({ code: 'USER_NOT_FOUND', message: 'User not found.' }); const oldRoles = user.roles.map(({ role }) => role.name); const removingAdmin = oldRoles.includes(RoleName.ADMIN) && !requested.includes(RoleName.ADMIN); if (removingAdmin && actorId === id) throw new BadRequestException({ code: 'SELF_ADMIN_ROLE_REMOVAL_BLOCKED', message: 'Administrators cannot remove their own ADMIN role.' }); if (removingAdmin) { const admins = await tx.userRole.count({ where: { role: { name: RoleName.ADMIN } } }); if (admins <= 1) throw new BadRequestException({ code: 'LAST_ADMIN_PROTECTED', message: 'The last ADMIN role cannot be removed.' }); } const roles = await tx.role.findMany({ where: { name: { in: requested } } }); if (roles.length !== requested.length) throw new BadRequestException({ code: 'ROLE_NOT_FOUND', message: 'One or more roles do not exist.' }); await tx.userRole.deleteMany({ where: { userId: id } }); await tx.userRole.createMany({ data: roles.map((role) => ({ userId: id, roleId: role.id })) }); await this.audit.record({ actorId, action: 'USER_ROLES_CHANGED', entityType: 'User', entityId: id, oldValues: { roles: oldRoles }, newValues: { roles: requested } }, tx); }); return this.user(id); }
 async summary() { const [total, active, suspended, disabled, verified, unverified, recentUsers, unreadNotifications, media] = await Promise.all([this.prisma.user.count(), this.prisma.user.count({ where: { status: UserStatus.ACTIVE } }), this.prisma.user.count({ where: { status: UserStatus.SUSPENDED } }), this.prisma.user.count({ where: { status: UserStatus.DISABLED } }), this.prisma.user.count({ where: { emailVerifiedAt: { not: null } } }), this.prisma.user.count({ where: { emailVerifiedAt: null } }), this.prisma.user.findMany({ take: 5, orderBy: { createdAt: 'desc' }, select: { id: true, email: true, createdAt: true, profile: { select: { firstName: true, lastName: true } } } }), this.prisma.notification.count({ where: { readAt: null } }), this.prisma.mediaAsset.count()]); return { users: { total, active, suspended, disabled, verified, unverified }, recentUsers, notifications: { unread: unreadNotifications }, media: { total: media } }; }
 async auditLogs(query: AuditLogQueryDto) { const where: Prisma.AuditLogWhereInput = { ...(query.actorUserId ? { actorId: query.actorUserId } : {}), ...(query.entityType ? { entityType: query.entityType } : {}), ...(query.entityId ? { entityId: query.entityId } : {}), ...(query.action ? { action: query.action } : {}), ...((query.from || query.to) ? { createdAt: { ...(query.from ? { gte: new Date(query.from) } : {}), ...(query.to ? { lte: new Date(query.to) } : {}) } } : {}) }; const [items, total] = await Promise.all([this.prisma.auditLog.findMany({ where, ...pagination(query), orderBy: { createdAt: query.sortOrder }, include: { actor: { select: { id: true, email: true } } } }), this.prisma.auditLog.count({ where })]); return pageResult(items, total, query); }
 async mediaList(query: AdminUsersQueryDto) { const [items, total] = await Promise.all([this.prisma.mediaAsset.findMany({ ...pagination(query), orderBy: { createdAt: query.sortOrder } }), this.prisma.mediaAsset.count()]); return pageResult(items, total, query); }
 async media(id: string) { const asset = await this.prisma.mediaAsset.findUnique({ where: { id } }); if (!asset) throw new NotFoundException({ code: 'MEDIA_ASSET_NOT_FOUND', message: 'Media asset not found.' }); return asset; }
 async createMedia(actorId: string, dto: CreateMediaDto) { const asset = await this.prisma.mediaAsset.create({ data: { ...dto, storageKey: dto.storageKey.trim(), url: dto.url.trim(), mimeType: dto.mimeType.trim(), altText: dto.altText?.trim(), uploadedById: actorId } }); await this.audit.record({ actorId, action: 'MEDIA_CREATED', entityType: 'MediaAsset', entityId: asset.id, newValues: { storageKey: asset.storageKey } }); return asset; }
 async uploadMedia(actorId: string, file: Express.Multer.File, altText?: string, context?: string) { const imageTypes = new Set(['image/jpeg','image/png','image/webp','image/avif']); const videoTypes = new Set(['video/mp4','video/webm','video/quicktime']); const resource = imageTypes.has(file.mimetype) ? 'image' : videoTypes.has(file.mimetype) ? 'video' : null; if (!resource) throw new BadRequestException({ code: 'MEDIA_TYPE_NOT_ALLOWED', message: 'This media type is not supported.' }); const max = resource === 'image' ? 10 * 1024 * 1024 : 100 * 1024 * 1024; if (file.size > max) throw new BadRequestException({ code: 'MEDIA_FILE_TOO_LARGE', message: `Maximum ${resource === 'image' ? 10 : 100} MB allowed.` }); let uploaded: any; try { uploaded = await this.storage.upload(file.buffer, resource, file.mimetype, context); const asset = await this.prisma.mediaAsset.create({ data: { storageKey: uploaded.publicId, url: uploaded.url, mimeType: uploaded.mimeType, sizeBytes: uploaded.bytes ?? file.size, width: uploaded.width, height: uploaded.height, altText: altText?.trim(), provider: 'CLOUDINARY', resourceType: uploaded.resourceType, format: uploaded.format, uploadedById: actorId } }); await this.audit.record({ actorId, action: 'MEDIA_UPLOADED', entityType: 'MediaAsset', entityId: asset.id, newValues: { provider: asset.provider, publicId: asset.storageKey, resourceType: asset.resourceType } }); return asset; } catch (error) { if (uploaded) { try { await this.storage.remove(uploaded.publicId, uploaded.resourceType); } catch {} } if (error instanceof BadRequestException) throw error; throw new ServiceUnavailableException({ code: 'MEDIA_UPLOAD_FAILED', message: 'Media upload failed.' }); } }
 async updateMedia(actorId: string, id: string, dto: UpdateMediaDto) { const old = await this.media(id); const asset = await this.prisma.mediaAsset.update({ where: { id }, data: { ...(dto.url ? { url: dto.url.trim() } : {}), ...(dto.altText !== undefined ? { altText: dto.altText.trim() } : {}) } }); await this.audit.record({ actorId, action: 'MEDIA_UPDATED', entityType: 'MediaAsset', entityId: id, oldValues: { url: old.url, altText: old.altText }, newValues: { url: asset.url, altText: asset.altText } }); return asset; }
 async deleteMedia(actorId: string, id: string) { const old = await this.media(id); const attached = await this.prisma.contentMedia.count({ where: { mediaAssetId: id } }); if (attached) throw new BadRequestException({ code: 'MEDIA_ASSET_IN_USE', message: 'Media asset is attached to published content and cannot be deleted.' }); if (old.provider === 'CLOUDINARY') { if (!this.storage) throw new ServiceUnavailableException({ code: 'MEDIA_PROVIDER_NOT_CONFIGURED', message: 'Media provider is not configured.' }); await this.storage.remove(old.storageKey, old.resourceType === 'VIDEO' ? 'VIDEO' : 'IMAGE'); } await this.prisma.$transaction(async (tx) => { await tx.mediaAsset.delete({ where: { id } }); await this.audit.record({ actorId, action: 'MEDIA_DELETED', entityType: 'MediaAsset', entityId: id, oldValues: { storageKey: old.storageKey, url: old.url } }, tx); }); return { message: 'Media asset deleted.' }; }
 settings() { return this.prisma.siteSetting.findMany({ orderBy: { key: 'asc' } }); }
 async setting(key: string) { const setting = await this.prisma.siteSetting.findUnique({ where: { key } }); if (!setting) throw new NotFoundException({ code: 'SETTING_NOT_FOUND', message: 'Setting not found.' }); return setting; }
 async updateSetting(actorId: string, key: string, dto: UpdateSettingDto) { if (/secret|password|token|database|smtp|jwt|payment.*key/i.test(key)) throw new BadRequestException({ code: 'FORBIDDEN', message: 'Secrets must not be stored in site settings.' }); const existing = await this.prisma.siteSetting.findUnique({ where: { key } }); const setting = await this.prisma.$transaction(async (tx) => { const saved = await tx.siteSetting.upsert({ where: { key }, update: { value: dto.value as Prisma.InputJsonValue }, create: { key, value: dto.value as Prisma.InputJsonValue } }); await this.audit.record({ actorId, action: 'SITE_SETTING_UPDATED', entityType: 'SiteSetting', entityId: saved.id, oldValues: existing ? { value: existing.value } : undefined, newValues: { value: saved.value } }, tx); return saved; }); return setting; }
 publicSettings() { return this.prisma.siteSetting.findMany({ where: { key: { in: [...publicSettings] } }, orderBy: { key: 'asc' } }); }
}
