import { BadRequestException } from '@nestjs/common';
import { HostelBookingStatus, Prisma } from '@prisma/client';
import { HostelService } from './hostel.service';
const d=(s:string)=>new Date(`${s}T00:00:00.000Z`);
describe('HostelService',()=>{
 const prisma:any={hostel:{findUnique:jest.fn()},roomType:{findUnique:jest.fn()},hostelBookingUnit:{findMany:jest.fn()},hostelBooking:{findFirst:jest.fn(),findUnique:jest.fn(),update:jest.fn()},$transaction:jest.fn((fn:any)=>fn(prisma))}; const audit:any={record:jest.fn()}; const email:any={sendNonBlocking:jest.fn()}; const service=new HostelService(prisma,audit,email);
 beforeEach(()=>jest.clearAllMocks());
 it('uses the strict overlap condition and excludes cancelled bookings',()=>{expect((service as any).overlap(d('2027-01-02'),d('2027-01-04'))).toEqual({checkInDate:{lt:d('2027-01-04')},checkOutDate:{gt:d('2027-01-02')},status:{in:[HostelBookingStatus.CONFIRMED,HostelBookingStatus.CHECKED_IN]}})});
 it('finds private rooms not allocated by overlapping blocking bookings',async()=>{prisma.roomType.findUnique.mockResolvedValue({id:'rt',isPrivate:true,rooms:[{id:'r1',beds:[]},{id:'r2',beds:[]}],priceRules:[],hostel:{}});prisma.hostelBookingUnit.findMany.mockResolvedValue([{roomId:'r1',bedId:null}]);const found=await (service as any).allocations('rt',d('2027-01-01'),d('2027-01-02'));expect(found.available).toEqual([{roomId:'r2'}])});
 it('finds available dorm beds independently',async()=>{prisma.roomType.findUnique.mockResolvedValue({id:'rt',isPrivate:false,rooms:[{id:'r1',beds:[{id:'b1'},{id:'b2'}]}],priceRules:[],hostel:{}});prisma.hostelBookingUnit.findMany.mockResolvedValue([{roomId:'r1',bedId:'b1'}]);const found=await (service as any).allocations('rt',d('2027-01-01'),d('2027-01-02'));expect(found.available).toEqual([{roomId:'r1',bedId:'b2'}])});
 it('calculates decimal seasonal nightly prices',()=>{const out=(service as any).pricing({basePrice:new Prisma.Decimal('100'),currency:'INR',priceRules:[{id:'rule',name:'Festival',startsOn:d('2027-01-02'),endsOn:d('2027-01-02'),nightlyRate:new Prisma.Decimal('125'),minNights:null,createdAt:d('2026-01-01')} ]},d('2027-01-01'),d('2027-01-03'),2);expect(out.subtotal).toBe('450.00');expect(out.nightlyBreakdown[1].rule.name).toBe('Festival')});
 it('rejects invalid booking dates',()=>expect(()=> (service as any).invalidDates('2027-01-02','2027-01-02')).toThrow(BadRequestException));
 it('cancels a pending booking and audits it',async()=>{jest.spyOn(service,'userBooking').mockResolvedValue({id:'b',status:HostelBookingStatus.PENDING} as any);prisma.hostelBooking.update.mockResolvedValue({id:'b',status:HostelBookingStatus.CANCELLED});await service.cancel('u','b');expect(prisma.hostelBooking.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({status:HostelBookingStatus.CANCELLED})}));expect(audit.record).toHaveBeenCalledWith(expect.objectContaining({action:'HOSTEL_BOOKING_CANCELLED'}),prisma)});
 it('does not allow users to cancel a checked-in booking',async()=>{jest.spyOn(service,'userBooking').mockResolvedValue({id:'b',status:HostelBookingStatus.CHECKED_IN} as any);await expect(service.cancel('u','b')).rejects.toThrow(BadRequestException)});
 it('allows only centralized valid admin status transitions',async()=>{jest.spyOn(service,'adminBooking').mockResolvedValue({id:'b',status:HostelBookingStatus.CONFIRMED,units:[]} as any);prisma.hostelBooking.update.mockResolvedValue({id:'b',status:HostelBookingStatus.CHECKED_IN});await service.updateBookingStatus('a','b',HostelBookingStatus.CHECKED_IN);await expect(service.updateBookingStatus('a','b',HostelBookingStatus.PENDING)).rejects.toThrow(BadRequestException)});
 it('sends a confirmation only after an admin confirmation transition commits',async()=>{jest.spyOn(service,'adminBooking').mockResolvedValue({id:'b',status:HostelBookingStatus.PENDING,checkInDate:d('2027-01-01'),checkOutDate:d('2027-01-02'),units:[]} as any);prisma.hostelBooking.update.mockResolvedValue({id:'b',bookingNumber:'HY-1',contactEmail:'persisted@example.com',status:HostelBookingStatus.CONFIRMED});await service.updateBookingStatus('a','b',HostelBookingStatus.CONFIRMED);expect(email.sendNonBlocking).toHaveBeenCalledWith('hostel-booking-confirmed','persisted@example.com',{bookingNumber:'HY-1'},{entityId:'b'});});
 it('re-checks a pending allocation before confirmation',async()=>{prisma.hostelBookingUnit.findFirst=jest.fn().mockResolvedValue({id:'existing'});jest.spyOn(service,'adminBooking').mockResolvedValue({id:'b',status:HostelBookingStatus.PENDING,checkInDate:d('2027-01-01'),checkOutDate:d('2027-01-02'),units:[{id:'u',roomId:'r',bedId:null}]} as any);await expect(service.updateBookingStatus('a','b',HostelBookingStatus.CONFIRMED)).rejects.toThrow(BadRequestException)});
});
