import { Body, Controller, Delete, Get, Param, Patch, Post, Put, Query, Version } from '@nestjs/common';
import { RoleName } from '@prisma/client';
import { Public } from '../auth/decorators/public.decorator'; import { Roles } from '../auth/decorators/roles.decorator'; import { CurrentUser } from '../auth/decorators/current-user.decorator'; import { AuthenticatedUser } from '../auth/types/authenticated-user.type';
import { HostelService } from './hostel.service'; import * as D from './dto/hostel.dto';
@Controller() export class HostelController { constructor(private readonly service: HostelService) {}
 @Public() @Get('hostels') @Version('1') hostels() { return this.service.hostels(); } @Public() @Get('hostels/:id') @Version('1') hostel(@Param('id') id: string) { return this.service.hostel(id); } @Public() @Get('hostels/:id/room-types') @Version('1') roomTypes(@Param('id') id: string) { return this.service.roomTypes(id); } @Public() @Get('room-types/:id') @Version('1') roomType(@Param('id') id: string) { return this.service.roomType(id); } @Public() @Get('hostels/:id/availability') @Version('1') availability(@Param('id') id: string, @Query() dto: D.StayDto) { return this.service.availability(id, dto); } @Public() @Post('hostels/:id/quote') @Version('1') quote(@Param('id') id: string, @Body() dto: D.QuoteDto) { return this.service.quote(id, dto); }
 @Post('hostel-bookings') @Version('1') create(@CurrentUser() user: AuthenticatedUser, @Body() dto: D.CreateBookingDto) { return this.service.createBooking(user.id, dto); } @Get('hostel-bookings') @Version('1') bookings(@CurrentUser() user: AuthenticatedUser, @Query() dto: D.BookingQueryDto) { return this.service.userBookings(user.id, dto); } @Get('hostel-bookings/:id') @Version('1') booking(@CurrentUser() user: AuthenticatedUser, @Param('id') id: string) { return this.service.userBooking(user.id, id); } @Post('hostel-bookings/:id/cancel') @Version('1') cancel(@CurrentUser() user: AuthenticatedUser, @Param('id') id: string) { return this.service.cancel(user.id, id); }
}
@Controller('admin') @Roles(RoleName.ADMIN) export class HostelAdminController { constructor(private readonly service: HostelService) {}
 @Get('hostels') @Version('1') hostels() { return this.service.adminHostels(); } @Post('hostels') @Version('1') createHostel(@CurrentUser() a: AuthenticatedUser,@Body() d:D.CreateHostelDto){return this.service.createHostel(a.id,d)} @Get('hostels/:id') @Version('1') hostel(@Param('id') id:string){return this.service.adminHostel(id)} @Patch('hostels/:id') @Version('1') updateHostel(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdateHostelDto){return this.service.updateHostel(a.id,id,d)} @Delete('hostels/:id') @Version('1') deleteHostel(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string){return this.service.deleteHostel(a.id,id)}
 @Get('hostels/:id/room-types') @Version('1') roomTypes(@Param('id') id:string){return this.service.roomTypes(id)} @Post('hostels/:id/room-types') @Version('1') createRoomType(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.CreateRoomTypeDto){return this.service.createRoomType(a.id,id,d)} @Patch('room-types/:id') @Version('1') updateRoomType(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdateRoomTypeDto){return this.service.updateRoomType(a.id,id,d)} @Delete('room-types/:id') @Version('1') deleteRoomType(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string){return this.service.deleteRoomType(a.id,id)}
 @Get('room-types/:id/rooms') @Version('1') rooms(@Param('id')id:string){return this.service.rooms(id)} @Post('room-types/:id/rooms') @Version('1') createRoom(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.CreateRoomDto){return this.service.createRoom(a.id,id,d)} @Patch('rooms/:id') @Version('1') updateRoom(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdateRoomDto){return this.service.updateRoom(a.id,id,d)} @Delete('rooms/:id') @Version('1') deleteRoom(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string){return this.service.deleteRoom(a.id,id)}
 @Get('rooms/:id/beds') @Version('1') beds(@Param('id')id:string){return this.service.beds(id)} @Post('rooms/:id/beds') @Version('1') createBed(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.CreateBedDto){return this.service.createBed(a.id,id,d)} @Patch('beds/:id') @Version('1') updateBed(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdateBedDto){return this.service.updateBed(a.id,id,d)} @Delete('beds/:id') @Version('1') deleteBed(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string){return this.service.deleteBed(a.id,id)}
 @Get('amenities') @Version('1') amenities(){return this.service.amenities()} @Post('amenities') @Version('1') createAmenity(@CurrentUser()a:AuthenticatedUser,@Body()d:D.AmenityDto){return this.service.createAmenity(a.id,d)} @Patch('amenities/:id') @Version('1') updateAmenity(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.AmenityDto){return this.service.updateAmenity(a.id,id,d)} @Delete('amenities/:id') @Version('1') deleteAmenity(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string){return this.service.deleteAmenity(a.id,id)} @Put('room-types/:id/amenities') @Version('1') setAmenities(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.AmenityAssignmentDto){return this.service.setAmenities(a.id,id,d)}
 @Post('rooms/:id/images') @Version('1') addImage(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.RoomImageDto){return this.service.addImage(a.id,id,d)} @Patch('room-images/:id') @Version('1') updateImage(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdateRoomImageDto){return this.service.updateImage(a.id,id,d)} @Delete('room-images/:id') @Version('1') deleteImage(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string){return this.service.deleteImage(a.id,id)}
 @Get('room-types/:id/price-rules') @Version('1') priceRules(@Param('id')id:string){return this.service.priceRules(id)} @Post('room-types/:id/price-rules') @Version('1') createPriceRule(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.PriceRuleDto){return this.service.createPriceRule(a.id,id,d)} @Patch('price-rules/:id') @Version('1') updatePriceRule(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdatePriceRuleDto){return this.service.updatePriceRule(a.id,id,d)} @Delete('price-rules/:id') @Version('1') deletePriceRule(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string){return this.service.deletePriceRule(a.id,id)}
 @Get('hostel-bookings') @Version('1') bookings(@Query()d:D.AdminBookingQueryDto){return this.service.adminBookings(d)} @Get('hostel-bookings/:id') @Version('1') booking(@Param('id')id:string){return this.service.adminBooking(id)} @Patch('hostel-bookings/:id/status') @Version('1') status(@CurrentUser()a:AuthenticatedUser,@Param('id')id:string,@Body()d:D.UpdateBookingStatusDto){return this.service.updateBookingStatus(a.id,id,d.status)}
}
