import { notFound } from "next/navigation";
import Link from "next/link";
import { SiteShell } from "@/components/shared/SiteShell";
import { StructuredContentRenderer } from "@/components/content/StructuredContentRenderer";
import { NewsletterSubscribe } from "@/components/content/NewsletterSubscribe";
import { getPublishedPost, thumbnail, gallery, formatPublishedDate } from "@/lib/content-public-api";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { try { const post = await getPublishedPost((await params).slug); return { title: `${post.title} | Nomad Yoga`, description: post.excerpt ?? undefined, alternates: { canonical: `/blog/${post.slug}` } }; } catch { return { title: "Newsletter | Nomad Yoga" }; } }
export default async function Article({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; let post; try { post = await getPublishedPost(slug); } catch { notFound(); } const images = gallery(post.media); return <SiteShell><article className="article-page"><div className="container article-head"><Link href="/blog" className="back-link dark">← Newsletter</Link><p className="eyebrow">{post.category?.name ?? "Newsletter"}{post.publishedAt ? ` · ${formatPublishedDate(post.publishedAt)}` : ""}</p><h1>{post.title}</h1>{post.excerpt && <p>{post.excerpt}</p>}<div className="content-tags">{post.tags?.map((tag) => <span key={tag.blogTag.name}>{tag.blogTag.name}</span>)}</div></div><div className="article-image"><img src={thumbnail(post.media, post.coverImageUrl ?? "/images/about/nomad-story.jpg")} alt={post.title} /></div><div className="container article-body"><StructuredContentRenderer blocks={post.body?.blocks} />{post.videoUrl && <p className="content-video"><a className="button button-small" href={post.videoUrl} target="_blank" rel="noreferrer">Watch video ↗</a></p>}{images.length > 0 && <div className="content-gallery">{images.map((item, index) => <figure key={item.id}><img src={item.mediaAsset.url} alt={item.mediaAsset.altText || `${post.title} — image ${index + 1}`} /><figcaption>{item.mediaAsset.altText || `From the newsletter · ${index + 1}`}</figcaption></figure>)}</div>}<div className="content-subscribe"><p className="eyebrow">Stay close</p><h2>Notes for the road ahead.</h2><p>Occasional practice notes and community updates from Nomad Yoga.</p><NewsletterSubscribe /></div></div></article></SiteShell>; }
