import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { BlogStatus, ContentMediaRole, MediaResourceType, Prisma } from '@prisma/client';
import { AuditService } from '../../common/audit/audit.service';
import { pageResult, pagination } from '../../common/pagination/pagination';
import { PrismaService } from '../../database/prisma.service';
import * as D from './dto/blog.dto';

@Injectable()
export class BlogService {
  constructor(private p: PrismaService, private a: AuditService) {}
  private mediaInclude = { media: { include: { mediaAsset: true }, orderBy: { sortOrder: 'asc' as const } } };
  private async post(id: string) { const x = await this.p.blogPost.findUnique({ where: { id }, include: this.mediaInclude }); if (!x) throw new NotFoundException({ code: 'BLOG_POST_NOT_FOUND', message: 'Blog post not found.' }); return x; }
  private async attachments(d: D.PostDto, blogPostId: string, tx: any) {
    const gallery = [...(d.galleryMediaAssetIds ?? [])];
    if (new Set(gallery).size !== gallery.length || (d.thumbnailMediaAssetId && gallery.includes(d.thumbnailMediaAssetId))) throw new BadRequestException({ code: 'DUPLICATE_MEDIA_ASSET', message: 'Media assets must be unique.' });
    const ids = [...(d.thumbnailMediaAssetId ? [d.thumbnailMediaAssetId] : []), ...gallery];
    if (!ids.length) { await tx.contentMedia.deleteMany({ where: { blogPostId } }); return; }
    const assets = await tx.mediaAsset.findMany({ where: { id: { in: ids } } });
    if (assets.length !== ids.length || assets.some((x: any) => x.resourceType !== MediaResourceType.IMAGE)) throw new BadRequestException({ code: 'INVALID_MEDIA_ASSET', message: 'Only existing image media assets may be attached.' });
    await tx.contentMedia.deleteMany({ where: { blogPostId } });
    await tx.contentMedia.createMany({ data: ids.map((mediaAssetId, i) => ({ blogPostId, mediaAssetId, role: i === 0 && d.thumbnailMediaAssetId ? ContentMediaRole.THUMBNAIL : ContentMediaRole.GALLERY, sortOrder: i })) });
  }
  async posts(q: D.BlogQueryDto) { const where: Prisma.BlogPostWhereInput = { status: BlogStatus.PUBLISHED, ...(q.category ? { category: { is: { OR: [{ id: q.category }, { slug: q.category }] } } } : {}), ...(q.tag ? { tags: { some: { blogTag: { is: { OR: [{ id: q.tag }, { slug: q.tag }] } } } } } : {}), ...(q.search ? { OR: [{ title: { contains: q.search, mode: 'insensitive' } }, { excerpt: { contains: q.search, mode: 'insensitive' } }] } : {}) }; const [items, total] = await Promise.all([this.p.blogPost.findMany({ where, ...pagination(q), orderBy: { publishedAt: 'desc' }, include: { ...this.mediaInclude, category: true, tags: { include: { blogTag: true } }, author: { select: { id: true, email: true } } } }), this.p.blogPost.count({ where })]); return pageResult(items, total, q); }
  async detail(slug: string) { const x = await this.p.blogPost.findFirst({ where: { status: BlogStatus.PUBLISHED, OR: [{ id: slug }, { slug }] }, include: { ...this.mediaInclude, category: true, tags: { include: { blogTag: true } }, author: { select: { id: true, email: true } } } }); if (!x) throw new NotFoundException({ code: 'BLOG_POST_NOT_FOUND', message: 'Blog post not found.' }); return x; }
  categories() { return this.p.blogCategory.findMany({ orderBy: { name: 'asc' } }); }
  tags() { return this.p.blogTag.findMany({ orderBy: { name: 'asc' } }); }
  async adminPosts(q: D.BlogQueryDto) { const where: any = { ...(q.status ? { status: q.status } : {}), ...(q.category ? { categoryId: q.category } : {}), ...(q.search ? { title: { contains: q.search, mode: 'insensitive' } } : {}) }; const [items, total] = await Promise.all([this.p.blogPost.findMany({ where, ...pagination(q), include: { ...this.mediaInclude, category: true, tags: { include: { blogTag: true } } } }), this.p.blogPost.count({ where })]); return pageResult(items, total, q); }
  adminPost(id: string) { return this.post(id); }
  async createPost(a: string, d: D.PostDto) { try { const x = await this.p.$transaction(async tx => { const created = await tx.blogPost.create({ data: { title: d.title, slug: d.slug, excerpt: d.excerpt, body: d.body as Prisma.InputJsonValue, coverImageUrl: d.coverImageUrl, categoryId: d.categoryId, status: d.status ?? BlogStatus.DRAFT, authorId: a, videoUrl: d.videoUrl, tags: { create: (d.tagIds ?? []).map(blogTagId => ({ blogTagId })) }, publishedAt: d.status === BlogStatus.PUBLISHED ? new Date() : undefined } }); await this.attachments(d, created.id, tx); return created; }); await this.a.record({ actorId: a, action: 'BLOG_POST_CREATED', entityType: 'BlogPost', entityId: x.id }); return this.post(x.id); } catch (e: any) { if (e?.status === 400) throw e; throw new ConflictException({ code: 'BLOG_SLUG_ALREADY_EXISTS', message: 'Blog slug or tag assignment already exists.' }); } }
  async updatePost(a: string, id: string, d: D.PostDto) { await this.post(id); try { const x = await this.p.$transaction(async tx => { await tx.blogPostTag.deleteMany({ where: { blogPostId: id } }); const updated = await tx.blogPost.update({ where: { id }, data: { title: d.title, slug: d.slug, excerpt: d.excerpt, body: d.body as any, coverImageUrl: d.coverImageUrl, categoryId: d.categoryId, status: d.status, videoUrl: d.videoUrl, tags: { create: (d.tagIds ?? []).map(blogTagId => ({ blogTagId })) }, publishedAt: d.status === BlogStatus.PUBLISHED ? new Date() : undefined } }); await this.attachments(d, id, tx); return updated; }); await this.a.record({ actorId: a, action: 'BLOG_POST_UPDATED', entityType: 'BlogPost', entityId: id }); return this.post(x.id); } catch (e: any) { if (e?.status === 400) throw e; throw new ConflictException({ code: 'BLOG_SLUG_ALREADY_EXISTS', message: 'Blog slug or tag assignment already exists.' }); } }
  async archive(a: string, id: string) { await this.p.blogPost.update({ where: { id }, data: { status: BlogStatus.ARCHIVED } }); await this.a.record({ actorId: a, action: 'BLOG_POST_ARCHIVED', entityType: 'BlogPost', entityId: id }); return { archived: true }; }
  async entity(kind: 'category' | 'tag', a: string, d: D.CategoryDto, id?: string) { const model: any = kind === 'category' ? this.p.blogCategory : this.p.blogTag; try { if (id) { const x = await model.update({ where: { id }, data: d }); await this.a.record({ actorId: a, action: `BLOG_${kind.toUpperCase()}_UPDATED`, entityType: kind, entityId: id }); return x; } const x = await model.create({ data: d }); await this.a.record({ actorId: a, action: `BLOG_${kind.toUpperCase()}_CREATED`, entityType: kind, entityId: x.id }); return x; } catch { throw new ConflictException({ code: `BLOG_${kind.toUpperCase()}_SLUG_ALREADY_EXISTS`, message: 'Slug already exists.' }); } }
  async deleteEntity(kind: 'category' | 'tag', a: string, id: string) { const count = kind === 'category' ? await this.p.blogPost.count({ where: { categoryId: id } }) : await this.p.blogPostTag.count({ where: { blogTagId: id } }); if (count) throw new BadRequestException({ code: 'BLOG_ENTITY_DELETE_NOT_ALLOWED', message: 'Entity has posts.' }); const model: any = kind === 'category' ? this.p.blogCategory : this.p.blogTag; await model.delete({ where: { id } }); await this.a.record({ actorId: a, action: `BLOG_${kind.toUpperCase()}_DELETED`, entityType: kind, entityId: id }); return { deleted: true }; }
}
